
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexico;

/** CUP generated interface containing symbol constants. */
public interface iXSymbols {
  /* terminals */
  public static final int CONS = 3;
  public static final int FUNCTION = 7;
  public static final int UMINUS = 27;
  public static final int LPAREN = 17;
  public static final int INT = 5;
  public static final int RPAREN = 18;
  public static final int REAL_LITERAL = 35;
  public static final int NOT = 33;
  public static final int SEMICOLON = 19;
  public static final int AND = 31;
  public static final int LT = 28;
  public static final int OR = 32;
  public static final int BOOL = 4;
  public static final int COMMA = 20;
  public static final int DIV = 25;
  public static final int ASSIGN = 21;
  public static final int IF = 9;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int MOD = 26;
  public static final int EQ = 30;
  public static final int LBRACK = 13;
  public static final int REAL = 6;
  public static final int LBRACE = 15;
  public static final int ELSE = 11;
  public static final int RBRACK = 14;
  public static final int WHILE = 12;
  public static final int THEN = 10;
  public static final int RBRACE = 16;
  public static final int SUM = 22;
  public static final int GT = 29;
  public static final int SUB = 23;
  public static final int VAR = 2;
  public static final int PROCEDURE = 8;
  public static final int BOOL_LITERAL = 36;
  public static final int INT_LITERAL = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "CONS",
  "BOOL",
  "INT",
  "REAL",
  "FUNCTION",
  "PROCEDURE",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "ASSIGN",
  "SUM",
  "SUB",
  "MUL",
  "DIV",
  "MOD",
  "UMINUS",
  "LT",
  "GT",
  "EQ",
  "AND",
  "OR",
  "NOT",
  "INT_LITERAL",
  "REAL_LITERAL",
  "BOOL_LITERAL",
  "ID"
  };
}

